### ISSUE TITLE
Create workflow to parse issue and make a PR adding *.tweet file

### ISSUE THREAD

**Issue by anubha-v-ardhan** [kubesimplify/tweets#15]
The idea is:
- Folks who want to tweet just write make an issue with tweet in issue description
- Parse the issue body to find tweet and make a PR committing the tweet as `./tweets/*.tweet` file
- On merging the PR, .tweet file is added to repo which triggers existing PR based workflow and tweet goes out from KubeSimplify's account

**Comment by anubha-v-ardhan** [comment]
I'm working on this, will let everyone know the progress soon.
Feel free to provide suggestions as I'm new to these

**Comment by AvineshTripathi** [comment]
do you wanna collaborate on this one or going solo, am ready to help @anubha-v-ardhan

**Comment by anubha-v-ardhan** [comment]
@AvineshTripathi Sure, I was thinking of this approach:

1. Make an issue template (use new issue forms feature)
2. Parse the issue using [stefanbuck/github-issue-parser](https://github.com/stefanbuck/github-issue-parser) to get data in JSON structure
3. Parse the JSON file using [jq](http://manpages.ubuntu.com/manpages/bionic/man1/jq.1.html) and echo it to tweets/{issue-number}.tweet file.
4. Use [peter-evans/create-pull-request](https://github.com/peter-evans/create-pull-request) to commit the {issue-number}.tweet file and open a PR


What do you think about the above approach, I can make a PR with yaml for above. Feel free to recommend any addition/subtraction/different-approach

**Comment by AvineshTripathi** [comment]
what additional feature does the `github-issue-parser` gives as we can get the body, issue-number, etc from the github api itself

**Comment by anubha-v-ardhan** [comment]
Correct me if I'm wrong but I guess using GitHub API will give whole issue body as one key-value pair which may not be the best solution for us as we want to present the user with a simple form (with title, instruction, placeholder text etc) and only fetch the actual tweet part and commit it to `.tweet` file.

github-issue-parser (or similar Actions) utilize the Issue form template and give each section as separate key-value pair in JSON. So it becomes easier to use for our use case.

**Comment by AvineshTripathi** [comment]
I see a yaml file for the form template, if that is the case I think we would have custom key-value pair(I have not tried it). We should try that once. The only concern with having some tool to do that job is that it becomes tough to maintain the flow as per our needs, working  with own code makes easier to update it into a better version accordingly

**Comment by anubha-v-ardhan** [comment]
I think the chances that we'll need more functionality from a parser is low but even If we do, we can always fork it and make our own action and use it instead.

However I'm in for having our own code from the start, can you test if it's possible to have key-value pairs from the issue body using the API itself?
else, we can write the action to parse issue ourselves, so we won't have to depend on [stefanbuck/github-issue-parser](https://github.com/stefanbuck/github-issue-parser)

**Comment by AvineshTripathi** [comment]
am actually trying to test it, probably they dont have that feature yet as its still beta. I ll try to come up with a potential solution by tomorrow for this thing particularly 

p.s. we should shift to slack or discord for discussion I would suggest

**Comment by anubha-v-ardhan** [comment]
Sure I'll start a thread on discord

**Comment by anubha-v-ardhan** [comment]
Sure, you can start a thread on discord :)
