### ISSUE TITLE
Create Issue form to go along with github-issue-parser

### ISSUE THREAD

**Issue by anubha-v-ardhan** [kubesimplify/tweets#16]
After discussing with folks, we have decided to use [stefanbuck/github-issue-parser](https://github.com/stefanbuck/github-issue-parser) to parse issue and output data as a JSON. (see #15)

We'll need an issue form to go along with it. We should have these on the form:
- name: New tweet request
- description: Create a new tweet request
- title: "[Tweet] <title>"
- markdown to tell user to take care of Twitter's character limit (280) and thanking them for make a new tweet request and that it will be merged soon and their tweet will go out
- Text Area for users to write their tweet with id: tweet, description: what do you want to tweet?, a nice placeholder, and make it a compulsory field for users
- Text Area for users with appropriate description and nice placeholder to tell why they want to tweet this (not compulsory to fill)
- Text Area for users with appropriate description and a nice placeholder to give any extra notes (not compulsory to fill)

Feel free to add/subtract/edit anything if you feel like from the above list. We can discuss about it before merging your PR

You can refer [syntax-for-issue-forms](https://docs.github.com/en/enterprise-cloud@latest/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) to write the yaml

**Comment by SuperAayush** [comment]
Hey! @anubha-v-ardhan can you please assign this issue to me?

**Comment by anubha-v-ardhan** [comment]
@SuperAayush I don't have privilege to assign but just commenting should be enough! You can start working

**Comment by SuperAayush** [comment]
@anubha-v-ardhan please close this issue
