### ISSUE TITLE
ADDING ISSUE TEMPLATE

### ISSUE THREAD

**Issue by vish-han** [kubesimplify/tweets#5]
There is no PR template in this repository yet. 

I would like to work on this issue if I get assigned😊.

**Comment by anubha-v-ardhan** [comment]
Sure go ahead!

**Comment by anubha-v-ardhan** [comment]
PRs will mostly be handled by github-actions bot.
Folks will need to create issue to tweet from KubeSimplify's account

If you're interested in creating an issue template instead, feel free to edit this issue's title to `Adding issue template` and work on the same

You can use [kubernetes-sigs/contributor-tweets's issue template](https://github.com/kubernetes-sigs/contributor-tweets/blob/main/.github/ISSUE_TEMPLATE/new-tweet-request.md) for reference

**Comment by vish-han** [comment]
@anubha-v-ardhan I would love to work on the issue template 🙋

**Comment by anubha-v-ardhan** [comment]
Thankyou @vish-han :)

**Comment by anubha-v-ardhan** [comment]
@vish-han Please wait for some time as we're still deciding if we "tweet via issue" or "tweet via PR"

**Comment by vish-han** [comment]
Ok bhia

**Comment by anubha-v-ardhan** [comment]
@vish-han We've decided to go with PR workflow temporarily and continue working to build an issue based workflow (see https://github.com/kubesimplify/tweets/pull/3#issuecomment-1086152031). I think it would be nice to create templates for both Issues and PRs

**Comment by vish-han** [comment]
Thanks @anubha-v-ardhan for letting me know about the changes,  I have my exam going on rn but I will try to make changes ASAP.😄

**Comment by saiyam1814** [comment]
Issue template is done
