### ISSUE TITLE
Create code-of-coduct.md for this project

### ISSUE THREAD

**Issue by anubha-v-ardhan** [kubesimplify/tweets#8]
Every open source project should have a code of coduct that establishes expectation of behaviour from contributors and everyone participating on the project.

KubeSimplify uses [CNCF code of conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

Add a file `code-of-conduct.md` stating above and linking to CNCF's code of conduct

**Comment by verma-kunal** [comment]
Hey @anubha-v-ardhan , i can do this one!

**Comment by anubha-v-ardhan** [comment]
Sure, go ahead!

**Comment by verma-kunal** [comment]
Except the link to [CNCF code of conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md), anything else to be added in there?

**Comment by verma-kunal** [comment]
> Except the link to [CNCF code of conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md), anything else to be added in there?

took reference from other CNCF projects! So, only adding the link would be sufficient 🙂
